### ISSUE TITLE
killed

### ISSUE THREAD

**Issue by hebrew878** [androguard/androguard#121]
![andro](https://cloud.githubusercontent.com/assets/2658040/9111535/99231622-3c65-11e5-88ca-1a79ed1abcb5.png)
why i am getting killed as output?

**Comment by adesnos** [comment]
We need more debug.

**Comment by LianlianMao** [comment]
i meet this error also.

**Comment by reox** [comment]
@LianlianMao can you give us more information? The file you tried to analyze, steps to replicate, your hardware, ...
It might be a problem with too much RAM usage.

**Comment by LianlianMao** [comment]
1.Here is some information about hardware:
(1)CPU:2.7GHz Intel,2 cpu, 8 cores per cpu, 2 threads per core.
(2)Memory:128G total, 120G used.

2.I am trying to analysis 2000 apk file. Because i am not sure all of these files are apk, i use this function 'androconf.is_android(filename)' to judge whether the file is apk before analysis it. Then I use the function 'misc.AnalyzeAPK(filename,session=None)' to start analysis apk. However, the process collapsed when finish the 141st apk.

Thanks!

**Comment by reox** [comment]
do you process the apks in multiple threads? Do you have a backtrace?
have you montiored the RAM usage while analysing?
Can you look into the syslog if the OOM killer is active?

**Comment by LianlianMao** [comment]
No, I only care my analysis result but ignore the RAM usage.
