### ISSUE TITLE
Add new depedencies 

### ISSUE THREAD

**Issue by adesnos** [androguard/androguard#213]
We need to specify the installation of:
future
pyasn1
cryptography
pyperclip (gui)

**Comment by adesnos** [comment]
pygments (gui)

**Comment by reox** [comment]
sphinx and sphinz-programoutput for documentation
networkx

I added them alread in the README.md and also in setup.py. I think the requirements.txt is only for travis, right? Otherwise i also would add them there

Also related: https://github.com/androguard/androguard/issues/48 and https://github.com/androguard/androguard/pull/142

**Comment by adesnos** [comment]
ipython for the androlyze

Yep for your question
