### ISSUE TITLE
[question] Parsing Android API Calls from APK

### ISSUE THREAD

**Issue by benldrmn** [androguard/androguard#282]
Hi,

is there any way, given an apk file, of retrieving the API calls used by the application with androguard? I look up a way in both androguard's code and documentation but couldn't find anything of that sort.

Thanks!

**Comment by reox** [comment]
basically all methods that are external are the API calls: https://github.com/androguard/androguard/blob/master/androguard/core/analysis/analysis.py#L634

You would need to iterate over all MethodClassAnalysis objects and check the xref's for such ExternalMethods.

HTH!

**Comment by benldrmn** [comment]
Hi, thanks for responding.
I'm not sure that's what I was looking for. I want to know which android API methods, such as getSystemService(), for example, are invoked by the app's code. I'm not interested in the method that called for the android API method, only to know whether a call to such method appears somewhere in the app's source code.

I know I can get a hold of all of the apk's classes\methods and parse them for strings like "getSystemService" in order to acquire this knowledge, but:
1. I wonder if there's a built-in solution in Androguard.
2. I'm not sure that the decompiler promises a valid decompiled class file (syntax-wise), and hence parsing may become problematic.

Thank you!

**Comment by reox** [comment]
Okay, so what you can try is to look if there is a method with this name _and_ is external. Then you can also check the xrefs, if the method is called.

For example, you can look for methods like this:
```
dx.get_method_by_name("Landroid/accounts/AccountManager;", "getAccounts", "()[Landroid/accounts/Account;")
```

I have to admit, this is not very usefull, because you need to know the exact name and descriptor.

Before, you had some methods to search for such calls, but they are removed because the whole Tainted stuff needs reworking.

ad 2) No, the code that comes out of the decompiler is probably not valid. I found already some issues with the syntax.
