### ISSUE TITLE
Warning when try to create DalivikVMFormat object, file attached.

### ISSUE THREAD

**Issue by waqarrashid33** [androguard/androguard#321]
I did came across a some apk files with which androguard is throwing warnings, but I am not sure whether it is because of androguard or because of  corrupt or invalid files. Please check the attached file.
[7f1b7ae2859bad220941924e2adea612.zip](https://github.com/androguard/androguard/files/1296322/7f1b7ae2859bad220941924e2adea612.zip)

To produce the error, remove the zip extension(just changed it for uploading):
`apk = APK("7f1b7ae2859bad220941924e2adea612")`

`Dvmformat = DalvikVMFormat(apk.get_dex())`

The message is:
`WARNING: unknown string item @ 0x2546(56)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/androguard-3.1.0-py2.7.egg/androguard/core/bytecodes/dvm.py", line 7285, in get_string
    return self.__strings_off[off].get()
KeyError: 9542
`

**Comment by reox** [comment]
I saw such things now several times.
The reason for this bug is, that the Offset in the MAP is not equal to the actual STRING_DATA section in the Header.

![real_string_data](https://user-images.githubusercontent.com/431045/30416782-b9ab14b8-992d-11e7-9481-df79e4c0ef28.PNG)
![fake_string_data](https://user-images.githubusercontent.com/431045/30416783-b9ab09a0-992d-11e7-8d9e-68d5dcac859d.PNG)

The Map item is definitively wrong.

I'm not sure how the Android DEX Parser handles such things, but it looks like he is not parsing the Map section but rather parsing the file flat from the start...

**Comment by reox** [comment]
As far as I can tell, these warnings can be ignored safely - as long as the DEX file parses correctly at the end.

If you believe that this is still a bug, please reopen the ticket!
