### ISSUE TITLE
AnalyzeAPK: memory leaking

### ISSUE THREAD

**Issue by hao555sky** [androguard/androguard#461]
There will be a problem when I use AnalyzeAPK mudule to annlyze apk in a multi-process environment. At first, I thought the reason is my local code, but after a long test, I found that it was a problem with the AnalyzeAPK module. 

So I hope that somebody can test this problem, and fix it if this problem really exists.

Thank you, excuse my poor English.

### System Information

- Androguard Version: master
- Python Version: 3.6/...
- Operating System

**Comment by reox** [comment]
> There will be a problem when I use AnalyzeAPK mudule to annlyze apk in a multi-process environment. At first, I thought the reason is my local code, but after a long test, I found that it was a problem with the AnalyzeAPK module.

Can you explain what kind of problem?

I assume the python process uses up a lot of RAM (judging from the title)... I had this issue before and after investigating in it, I can tell you that this is not a memory leak but due to memory fragmentation of the python process itself. But if you are using multiprocessing, just use subprocesses. If your analysis function has finished, all the memory will be freed. Unfortunately, there is no other way, as python is designed that way (at least there is no other way I know about).

**Comment by reox** [comment]
Maybe related: #403 
There might be some tweaks to reduce the footprint by a few MB, but I fear this is all what is possible.

**Comment by hao555sky** [comment]
@reox 
I am sorry for late reply and thank for your answer.
I am sure that the problem of memory growth is caused by AnalyzeAPK module. I have tested two scenarios, one using AnalyzeAPK module, and one not. The first one occurs memory growth, and the second will keep memory stable. 
The version of androguard 3.0 performs well, even if I use multiprocessing. But version of androguard 3.1 will keep memory growth, it will fill my 126G memory, and will not stop until I kill it. 
And I will try your suggestion about using subprocesses.
Thank you for your reply, please tell me if my problem description confused you.

**Comment by reox** [comment]
Oh wow, you have a lot of memory!

Do you use a Session? Can you test to reset the session after every call to `AnalyzeAPK`? Like CONF["SESSSION"].reset()

Otherwise, can you monitor what is going on using some python memory profiling tools? Like pympler or other tools.. you can probably use the tools mentioned here: https://stackoverflow.com/questions/1435415/python-memory-leaks

**Comment by hao555sky** [comment]
The large memory machine is a server in my lab, LOL.

I have tried your suggestion about CONF['SESSION'].reset(), it works. Now It almost cost  6G memory when I use 26 processes. Amazing, but in fact I don't know why, can you explain it to me if you have time? 

Thank you very much, have a good time.

**Comment by reox** [comment]
okay, then I understand what the problem is - you are actually not memory leaking, but storing all old analysis.
The Session is used for exactly this purpose: be able to add several APKs / DEX files, then work with them, save the session to disk, load it again and so on.
If you are doing some automated analysis, you probably do not want this behaviour - as you are not interested in keeping old stuff, you already have analysed or maybe even stored in some other format (at least I do such stuff).
If you set the session parameter in `AnalayseAPK` to None, the Default session is used - as I fixed that recently, you will actually always get the same session, thus add more and more APKs to it.

What I can, and will do, is to change the behaviour of AnalyzeAPK and AnalyzeDEX to use no session at all, if session=None.

**Comment by hao555sky** [comment]
Oh, I see. 

I see that it will get default seesion if the session parameter is None. So the default session will store all apk's analysis, but how can I use no session? 

And will the session clear itself automatically if I don't use default session but changed session with apk?

Thank you.

**Comment by hao555sky** [comment]
OK, thank you very much.
