### ISSUE TITLE
need apkviewer in androgurad 3 for python 3

### ISSUE THREAD

**Issue by sasansasansasansasan** [androguard/androguard#482]
i need apkviewer for extract call graph
in androguard 3, i cant find apkviewer.
does it exists in androgurad 3?
 How to get Call graph using Androguard3?

**Comment by reox** [comment]
apkviewer was removed around 2014...
you can create callgraphs using the new tool androcg.py: http://androguard.readthedocs.io/en/latest/tools/androcg.html

**Comment by reox** [comment]
btw to extract control flow graphs, you can use androdd: http://androguard.readthedocs.io/en/latest/tools/androdd.html

**Comment by reox** [comment]
btw: do you know anything that is missing from the old apkviewer?

**Comment by AkshatSood** [comment]
> btw to extract control flow graphs, you can use androdd: http://androguard.readthedocs.io/en/latest/tools/androdd.html

Is there a way to generate the CFGs in a format other than png?

**Comment by reox** [comment]
```
  -f, --format TEXT      Additionally write control flow graphs for each
                         method, specify the format for example png, jpg, raw
                         (write dot file), ...
```

**Comment by AkshatSood** [comment]
I need the file in a format that I can then edit and work with, like JSON, GraphML or GML. 
When I tried running the decompile command with "raw" as the specified format, the command ran without any errors, but there was no output file. In the output folder, it created the "android" and "com" subfolders, but no graph file. 

I used the following command: 
`androguard decompile -o outputfolder -i application.apk -f raw`

**Comment by reox** [comment]
please check the code here: https://github.com/androguard/androguard/blob/8d091cbb309c0c50bf239f805cc1e0931b8dcddc/androguard/core/bytecode.py#L461

The function creates the dot graph and then writes it.
The issue is, that the method -> dot conversion is hardcoded here: https://github.com/androguard/androguard/blob/8d091cbb309c0c50bf239f805cc1e0931b8dcddc/androguard/core/bytecode.py#L227

There is also https://github.com/androguard/androguard/blob/8d091cbb309c0c50bf239f805cc1e0931b8dcddc/androguard/core/bytecode.py#L541 but I have no idea anymore what that does and if it works...
