### ISSUE TITLE
Clarification of app_name

### ISSUE THREAD

**Issue by Bubu** [androguard/androguard#501]
We now use androguard for parsing all built apks for f-droid.org for extracting app name, permissions and icons (I think). 

This sometimes creates unexpected results like this: https://f-droid.org/packages/community.fairphone.fplauncher3/

This is this app: https://github.com/WeAreFairphone/android_packages_apps_FairphoneLauncher3

And arguably the app name should be "Fairphone Launcher 3" as this is the defined application label. Androguard seems to return the name of the main activity instead.

First question, is that observation correct? If yes, what's the reasoning behind this?

Second question: why isn't the actual [launcher activity](https://github.com/WeAreFairphone/android_packages_apps_FairphoneLauncher3/blob/master/AndroidManifest.xml#L92) the main activity of the app? Where does this come from?

**Comment by reox** [comment]
Interessting - I get '* HPROF' as app name :D 

I think the logic of the function should be changed.
Currently it first looks for the main activity, then for the application label...

I changed that now in #502


For the main activity: androguard looks for an activity which has both action MAIN and category LAUNCHER.
The Manifest of the app is rather complex and there are several such activities... 
I'm not sure how you can determine which one is the main activity here?
The Launcher acitivy does not have category Launcher, thus it is not taken into account...

For the memory activity: The problem here is, that the boolean value is returned from the resources. I think this is currently not even checked...
```
[...]
if activityEnabled is not None and activityEnabled != "" and activityEnabled == "false":
[...]
```
We probably need a better parser for that, which resolves such things on the fly.
