### ISSUE TITLE
get_min_sdk_version() returns None for Chrome v70 minSdkVersion 24

### ISSUE THREAD

**Issue by fifi-l** [androguard/androguard#569]
### Describe what you wanted to do

`apk.get_min_sdk_version()`, `apk.get_target_sdk_version()` return None on Chrome apk v70 minAPI 24 downloaded from akpmirror (https://www.apkmirror.com/apk/google-inc/chrome/chrome-70-0-3538-64-release/google-chrome-fast-secure-70-0-3538-64-6-android-apk-download/download/). 
The same functions return correct values for Chrome apk v70 minAPI 21

### System Information

- Androguard Version: master
- Python Version: 2.7
- Operating System mac osx high sierra

### Further Log Files and Output

- please report logs, tracebacks and other useful information
- if possible report the files you tried to analyze!

**Comment by reox** [comment]
@fifi-l I think this is fixed with the changes in #592 
It looks like that they do not use a namespace mapping explicitly, and this was actually wrongly implemented in the AXMLParser. It would only print out the namespace if a mapping existed.

Can you test with the changes in the PR, please? Would be nice to know if it works for you too!
