### ISSUE TITLE
How to extract API method calls from dex file using androguard...?

### ISSUE THREAD

**Issue by SamiraSadat** [androguard/androguard#696]
I'm interested to implement an android app's malware detection with deep learning methods.
The Neural Network's input is **the raw sequence of the app's API method calls** which must be extracted from the DEX files. I have written a code to do this. Would you please check it in order Not to have a mistake. Great Thanks:)

```
from androguard.misc import AnalyzeAPK
import os
import time

def EXTRACT_METHOD_CALLS(a):
    app, list_of_dex, dx = AnalyzeAPK(a)
    for method in dx.get_methods():
        file.write("inside Method {} ".format(method.name) + ':' + '\n')
        for _, call, _ in method.get_xref_to():
            file.write("    calling -> {} -- {}".format(call.class_name, call.name) + '\n')


begin = time.time() 
 
for apk in os.listdir():
    file_name , file_extension = os.path.splitext(apk)
    file = open(file_name + '.txt', 'w')
    EXTRACT_METHOD_CALLS(apk)
    file.close()


end = time.time()

print(end-begin)
```

**Comment by reox** [comment]
I'm not sure if I understand the topic correctly, but if you say "sequence of the app's API method calls", you need the order or not? If you need the order, you should sort by the offset you get as the third value of the return tupe from `get_xref_to`.
Next, you never specify what do you mean by "API method calls". Then, you can filter the XREFs according to your definition of that and proceed from there.
If you take a look at several dex files, you will see that not only `java.*` or `android.*` are regarded as external classes, but all kinds of classes are external, as they are loaded dynamically. Thus you really need to specify what is an API and what is just not resolved at the time of Analysis.

Malware detection using deep learning sounds very interesting!

**Comment by SamiraSadat** [comment]
As a matter of fact, I couldn't understand what 'API Method calls' mean exactly just like U...:)
I saw it in a journal paper and asked them to explain but didn't answer.

**Comment by SamiraSadat** [comment]
Hi again :) 
As you know, API is an interface which helps Applications or software talk to together. Suppose that you decide to develop an application like Uber which helps taxi drivers find their paths. 
how do you work on it...?
 1) you can sit and develop a complete map for your application
2) use google map API.

Now if come back to our problem, most of the applications written in Java and use Android APIs.
by this explanation, the above code does this or not...! :)

**Comment by reox** [comment]
I know what an API is ;) But what you mean by "sequence of ...." is not clear.
One problem is, that branches inside the method lead to different code paths on execution time.
One big question is now how you can normalize this in order to give the same sequence for the same code.
For example, what if you have two code blocks, one like `if x > 0 then A else B` and the other like `if x <= 0 then B else A`. In both cases the code leads to the same result, but if you just dump the sequence inside the bytecode you end up with `A B` for the first case and `B A` for the second one.

Yet another problem is the exact definition of API. Obvious there are very many different APIs on Android. First of all there is the Java API. Then there is the Android API, then the GCM API, Google Play Services, ... And then there are apps using dynamically loaded code - which looks like an API for androguard, as the reference to the method can not be statically determined.
In order to only gather the "official" APIs , you need to come up with some sort of whitelist - which is very hard!

**Comment by its-me-abi** [comment]
hi androguard is a good tools but many of code are broken and undocumented.
for example i tested  method.get_xref_to():  it returns an empty set.

**Comment by ghadeer1** [comment]
@SamiraSadat  and @reox  can you guide me on how to extract API method calls from an APK of an Android app using AndroGuard?
