### ISSUE TITLE
How to generate JSON report for an APK 

### ISSUE THREAD

**Issue by dexter0810** [androguard/androguard#708]
Hi, to test whether an app is malicious, koodous generates a json report. We can then test on this json report yara ruleset which use the androguard module right? Please correct me if I'm wrong.
These json reports aren't available for all APK files on the site. Moreover, I wanted to test on an apk which I'm installing by offline means, so can you please tell me how to generate it's json report so that I can test the yara rules on it??

Is there a way to test the yara rules on the APK file without requiring the json file?

Any help is much appreciated.

**Comment by reox** [comment]
Koodous has not released the code to generate the reports as far as i know.  
Please ask the koodous staff for more information.

**Comment by reox** [comment]
I remember asking the koodous staff if they have the tool released somewhere. This was their answer in April 2018:

> You can run androguard locally and get all the information provided in that section.

I ended up creating some tool which creates a JSON file similar to the one of koodous - but it is very very hard to replicate the functionalities, as I have no idea which APIs they scan for. However, I can unfortunately not share this script with you either... But in order to get the basic sections working (everything without functionalities) it just took a morning to implement. I even found some bugs in their reports and reported them.

**Comment by dexter0810** [comment]
Hi, thanks for taking the time to help me out, I appreciate it :) 

How can I run androguard locally? I tried yara rule.yar sample.apk, that doe snot work. I evn tried yara rule.yar classes.dex, that didn't work either. Am I right?

So, how can I detect malwares in an app using the androguard module in a yar.file and using the apk( or a decompiled apk) ?

**Comment by reox** [comment]
The koodous stuff is a little bit different. First, you need the JSON file. Then you can run yara and add the json file to the commandline: https://github.com/Koodous/androguard-yara#using-androguard-module

With "running androgaurd locally" they mean, you need to write a tool which uses androguard to generate the report which you would need to download from their website otherwise.
Unfortunately, this tool is not released by koodous - at least not to my knowledge!
If you find it, please let me know!

**Comment by dexter0810** [comment]
I surely will. 
Thank you for helping me out. :)
