### ISSUE TITLE
Requested API Level could not be found, using 19 instead

### ISSUE THREAD

**Issue by SamiraSadat** [androguard/androguard#747]
Hi. I want to collect all permissions of some applications and build a database.
I extracted the permissions using **apk** submodule and a function which runs for each app in the directory:

```
from androguard.core.bytecodes import apk

def EXTRACT_PERMISSION(a):
    app = apk.APK(a)
    permission = app.get_permissions()
    for p in permission:
          print(p)

for app in os.listdir():
    EXTRACT_PERMISSION(app)
```

but, while extracting permission, I could see these notes in the ipython console:
- Requested API Level could not be found, using 19 instead
- Requested API Level could not be found, using 10 instead
- Failed to get the attribute 'name' on tag 'uses-permission' with namespace. But found the same attribute without namespace!
- Failed to get the attribute 'name' on tag 'permission' with namespace. But found the same attribute without namespace!
and like so.
- Name 'android:theme' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.
- Name 'android:exported' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.
and like so.

Is there any permission that didn't extract?
what's wrong with that and what can I do?

**Comment by reox** [comment]
> Requested API Level could not be found, using 19 instead

There is no permission description found for the API level of the APK and the heuristic chose this level to get some results. If you dont use the permission descriptions, everything is fine,

>    Requested API Level could not be found, using 10 instead

Same as above.

>    Failed to get the attribute 'name' on tag 'uses-permission' with namespace. But found the same attribute without namespace!

This is some packer doing weird stuff... Basically there is some xml tag which looks like this:

```
<uses-permission name="foobar">
```
instead of the correct one:
```
<uses-permission android:name="foobar">
```

Android does not seem to care about that, but in androguard we check this.

>    Failed to get the attribute 'name' on tag 'permission' with namespace. But found the same attribute without namespace!

same as above


>    Name 'android:theme' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.

This is again some issue with the AXML file format. In the format, there are two fields for the namespace and the actual name of the attribute.
There are some files which put both namespace and name into the name field, i.e. the namespace is then empty and the name contains a colon. A name with a colon is invalid xml, hence we throw this warning. Again, Android does not seem to care about this, but androguard does.

>    Name 'android:exported' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.

Same issue as above.

**Comment by reox** [comment]
The assumption is, that `android:name` is equal to `name`. Hence, it is added.

The warning is there to indicate that something is going on with the manifest file. If you encounter such warnings, you should probably treat the results with special care, as some packers might mess with the parsers to infer wrong results.
