### ISSUE TITLE
Calling `pickle.dump()` on an APK object corrupts the APK

### ISSUE THREAD

**Issue by thejager** [androguard/androguard#756]
### Describe what you wanted to do
I'm trying to write the results of  `AnalyzeAPK()` to a file, so that I don't have to re-run the analysis every time. However, after calling `pickle.dump()`, `a` gives errors for certain functions, like `get_activities()`

**EDIT: I see what I'm trying to solve can be done with sessions. Still I think it's weird that this happens. Anyways, feel free to close it if you don't think it's worth attention.**

```
>>> a, d, dx  = AnalyzeAPK("apks/bf_browser.apk")
>>> a
<androguard.core.bytecodes.apk.APK object at 0x7f1336603b38>
>>> a.get_activities()
['com.bfbrowser.powersurf.activity.ErrorPageActivity', 'com.bfbrowser.powersurf.Splash_screen', 'com.bfbrowser.powersurf.MainActivity', 'com.bfbrowser.powersurf.BrowserAivaActivity', 'com.bfbrowser.powersurf.activity.TermsAndConditionsActivity', 'com.bfbrowser.powersurf.activity.SettingsActivity', 'com.bfbrowser.powersurf.activity.ShareUrlWithQRCodeActivity', 'com.google.android.gms.common.api.GoogleApiActivity', 'com.google.android.gms.ads.AdActivity']
>>> import pickle
>>> pickle.dump(a, open('test.pickle', 'wb'))
>>> a.get_activities()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/johan/Projects/atsp/venv/lib/python3.5/site-packages/androguard/core/bytecodes/apk.py", line 1104, in get_activities
    return list(self.get_all_attribute_value("activity", "name"))
  File "/home/johan/Projects/atsp/venv/lib/python3.5/site-packages/androguard/core/bytecodes/apk.py", line 906, in get_all_attribute_value
    tags = self.find_tags(tag_name, **attribute_filter)
  File "/home/johan/Projects/atsp/venv/lib/python3.5/site-packages/androguard/core/bytecodes/apk.py", line 985, in find_tags
    for i in self.xml
  File "/home/johan/Projects/atsp/venv/lib/python3.5/site-packages/androguard/core/bytecodes/apk.py", line 985, in <listcomp>
    for i in self.xml
  File "/home/johan/Projects/atsp/venv/lib/python3.5/site-packages/androguard/core/bytecodes/apk.py", line 998, in find_tags_from_xml
    xml = self.xml[xml_name]
TypeError: string indices must be integers
```

### Describe what you expected
I expected it to give the list of activities.

### Describe what actually happened
Threw an error after `pickle.dump()` was called.

### System Information

- Androguard Version: 3.3.5
- Python Version: 3.55
- Operating System: Linux

**Comment by reox** [comment]
I think the problem here might be, that we have to remove some stuff from the APK object in order to be pickleable.
So it looks like after the object is pickled, it is burned and can not be used anymore...

I would guess if you unpickle it, it would work.

**Comment by thejager** [comment]
So I see that Sessions use pickle as well, making them not work at all.

```
>>> sess.analyzed_apk['4fc76fc0bc92f87900f8588e8e3d1988f838199a9ffec4a4d434ba7dcf73c5e5'][0].get_activities()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/johan/Projects/atsp/venv/lib/python3.7/site-packages/androguard/core/bytecodes/apk.py", line 1104, in get_activities
    return list(self.get_all_attribute_value("activity", "name"))
  File "/home/johan/Projects/atsp/venv/lib/python3.7/site-packages/androguard/core/bytecodes/apk.py", line 906, in get_all_attribute_value
    tags = self.find_tags(tag_name, **attribute_filter)
  File "/home/johan/Projects/atsp/venv/lib/python3.7/site-packages/androguard/core/bytecodes/apk.py", line 985, in find_tags
    for i in self.xml
  File "/home/johan/Projects/atsp/venv/lib/python3.7/site-packages/androguard/core/bytecodes/apk.py", line 985, in <listcomp>
    for i in self.xml
  File "/home/johan/Projects/atsp/venv/lib/python3.7/site-packages/androguard/core/bytecodes/apk.py", line 998, in find_tags_from_xml
    xml = self.xml[xml_name]
TypeError: string indices must be integers

```

**Comment by thejager** [comment]
So there's no way for me to save the analysis? Right now I have to re-run the analysis every time I change my code.

**Comment by reox** [comment]
No, pickling should work. But the problem seems to be, that you can not call things on the APK object after the pickling.

**Comment by SimonTor** [comment]
Hallo everyone,
I have a similar problem like theJager.
If I save my AndroGuard session I can not longer use the results from the analysis.

-------------------------------

If I execute:
`sess = misc.get_default_session()`
`a, d, dx = misc.AnalyzeAPK(APK_path, session=sess)`

the APK inside my session looks like:

![image](https://user-images.githubusercontent.com/23102400/106459049-93f0cf00-6491-11eb-89f9-6de8fa49f7ba.png)

There you can see that the APK contains a dict with one entry called"axml", a "xml" file and a "zip" file.

If I enter:
`sess.analyzed_apk[KEY][0].get_android_manifest_axml().get_xml()` 
I get the manifest

-------------------------------

After saving this session with
`session.Save(self.session_before_save, save_path)`
my session looks like this:
(this is the same object than before. It is not the restored one. It looks like pickle modifies and destroys my session object)

 ![image](https://user-images.githubusercontent.com/23102400/106459254-ddd9b500-6491-11eb-83cc-9f5bb36f96cc.png)

Now the "axml" and "xml" file is only a string and the zip file disappears completely.

If I enter:
`sess.analyzed_apk[KEY][0].get_android_manifest_axml().get_xml()` 
I get the error: {TypeError}string indices must be integers

-------------------------------

After loading the session file with
`sess = session.Load(load_path)`
it looks like:

![image](https://user-images.githubusercontent.com/23102400/106459434-23967d80-6492-11eb-90ec-397dc07a1295.png)

Now the "zip" file is back but the "axml" and "xml" files are only strings . 

During the command:
`sess.analyzed_apk[KEY][0].get_android_manifest_axml().get_xml()` 
I also get the error: {TypeError}string indices must be integers.

-------------------------------

Is there any possiblility to get my session back in a way that the session is usable?
I cannot access the manifest, the permissions and the intents after saving and/or loading the session.

-------------------------------

One additional comment:
To save and load a session I must run the save and load functions in a separate thread because it looks like that the recursion limit and the stack size are not large enough. Is this normal or did I use AndroGuard in a wrong way?

    sys.setrecursionlimit(1000000)
    threading.stack_size(200000000)
    session_test = SessionTest()
    session_path = ".../APK-info-extractor/testSessionSave.ag"
    save_thread = threading.Thread(target=session_test.test_session_save, args=(session_path,))
    save_thread.start()
    save_thread.join()
    load_thread = threading.Thread(target=session_test.test_session_load, args=(session_path,))
    load_thread.start()
    load_thread.join()

-------------------------------

I also test this with the beta but in the beta the recursion limit is set inside the AndroGuard save function to a small value. So I have to modify the AndroGuard file itself. It would be great if the user could make the recursion limit and the stack size parameterizable. 
Furthermore, with the beta it is also not possible to save and load the session in a way that you can reuse the results of the analysis .

**Comment by xiaoski** [comment]
I've found a similar phenomenon that as soon as deepcopy occurs, the previous parsing results become unusable.

```
apk, dex, vm = AnalyzeAPK("dummy.apk")
apk.get_receivers()  # ok
copy.deepcopy(apk)
apk.get_receivers()   # throw TypeError
```
