### ISSUE TITLE
Please cut a release at some stable point

### ISSUE THREAD

**Issue by blshkv** [androguard/androguard#903]
Please remove this template if you only have a question or do not want to create a new issue.

### Describe what you wanted to do

The latest release was back in 2020, however I see daily updates

### Describe what you expected
Periodic releases

### Describe what actually happened
Nothing ;-)

### System Information

- Androguard Version: master

**Comment by totoag** [comment]
it will be :)

**Comment by blshkv** [comment]
you haven't established the release cycle, sad to see it.

**Comment by erev0s** [comment]
@blshkv indeed we are far from a full release cycle but there have been important steps towards this goal since you first created this issue, along with a new release in [PyPI](https://pypi.org/project/androguard/) after a long time.

Next steps are to improve the test coverage and in general streamline further the process.

Given this is an open source project feel free to contribute or make suggestions for improvements.

**Comment by blshkv** [comment]
So here is my first suggestion: do not close the issue if it is not fixed ;-)
FYI, I'm a Pentoo developer and monitor hundreds of projects. That open source project makes my quite busy, so I would not be able to contribute a code or do a project management for you. However, I will be happy to test the release and help to fix any potential project with installation.

**Comment by erev0s** [comment]
@blshkv hehe fair point :)
the reason i closed it was due to the request was for a release and not setting up a full release cycle.
Release 4.0.0 was out when closed and yesterday patch update release 4.0.1 was available as well.

Though, you are right, it is a good idea to create another issue to keep track of the progress of a full release cycle and maybe given your experience you can help out in setting up which steps should/could/would ([moscow](https://en.wikipedia.org/wiki/MoSCoW_method) style) be covered.
