### ISSUE TITLE
Invalid uleb128 decoding, idx_diffs for Encoded*

### ISSUE THREAD

**Issue by rytilahti** [androguard/androguard#98]
Some elements are not read correctly, causing *Invalid objects to be created for them. Sounds like a decoding issue, but after doing some digging I couldn't find the cause. Btw, the biggest values are 32b full of 1s.

Dexdump has no issues reading that file.

Example APK is hosted on http://tepr.in/~tpr/temp/androguard_broken.apk . Here's an excerpt from androlyze shell for that file.

In [11]:  for i in d.get_classes():
        for x in i.get_methods():
                print "idx: %i" % x.get_method_idx_diff()
   ....:  
idx: 4
idx: 5
idx: 7
idx: 4294967292
idx: 1
idx: 4294967293
idx: 1
idx: 10
idx: 13
idx: 1
idx: 3
idx: 4294967295
idx: 4294967295
idx: 18
idx: 19
idx: 20
idx: 21
idx: 22
idx: 23
idx: 24

**Comment by adesnos** [comment]
probably due the the last pull request

**Comment by adesnos** [comment]
Can you tell me the problem exactly ? Is it with the latest git version ?

**Comment by teprrr** [comment]
It's not a new issue, but I have seen it already almost a year ago (iirc). This was tested with the latest git version, as well as one from approx. a year ago.

The problem is, that those indexes are obviously incorrect, although I'm not sure if it's the fault of DEX file here, or whether androguard reads it incorrectly. Nevertheless dexdump reads it correctly. Here's another snippet, printing out the names and descriptors:

In [6]:  for i in d.get_classes():
    for x in i.get_methods():
       print("%s %s" % (x.get_name(), x.get_descriptor()))
   ...:       
<init> ()V
<init> ()V
testReflection ()V
AG:IMI:invalid_name ()AG:IMI:invalid_proto
AG:IMI:invalid_name ()AG:IMI:invalid_proto
AG:IMI:invalid_name ()AG:IMI:invalid_proto
AG:IMI:invalid_name ()AG:IMI:invalid_proto
onCreate (Landroid/os/Bundle;)V
<init> ()V
bM_getDefault_122817834 ()Ljava/lang/Object;
bM_valueOf_66284459 (I)Ljava/lang/Object;
AG:IMI:invalid_name ()AG:IMI:invalid_proto
AG:IMI:invalid_name ()AG:IMI:invalid_proto
send (Ljava/lang/String;)V
<init> ()V
<init> ()V
<init> ()V
<init> ()V
<init> ()V
<init> ()V

**Comment by reox** [comment]
@rytilahti is it possible to reupload the APK? I would like to have a look at it!

**Comment by reox** [comment]
If this issue still occurs, please reopen!
